sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

before_install:
    - sudo apt-get update

install:
    - pip install -r requirements.txt
    - pip install sklearn
    - pip install pandas

script:
    - python setup.py install
    - coverage run example.py

after_success:
    - codecov