language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

before_install:
    - sudo apt-get update

install:
    - pip install -r requirements.txt
    - pip install sklearn

script:
    - python setup.py install
    - python example.py
